message: This is a message defined in the configuration file config.yaml.
messageRepetitions: 3
database:
    driverClass: org.hsqldb.jdbc.JDBCDriver
    user: SA
    password: Passw0rd
    url: jdbc:hsqldb:hsql://localhost/cpsc476;ifexists=true